apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgis-basic-auth
  namespace: time4games-prod
spec:
  encryptedData:
    auth: AgA8tjjUl1O0vGfq6/GTrS5P1pXnnnfj5s2OH54sQEIQ6dbEMZIG1LehF1Gvy84U9t/J7NJwKe2hK5wpPql/AD1DD0htckNTNbeZvw5efxpvZopWBlgaysLJCDicAF7e5BbKb1NP7X6j4mL6JtLJQKgpHxqGex86HJ0QHBbEVMWVpofj+cNbjNUemUXk20bdGfHcxuA9OBye8pfI3ChUX5wlaqAjLAeRRGWt+Hussk2P7zyXw0BD5bR/XQz66f+wjAF0wt6zk8oeK6aGkWE0tF9pk6xirfPzLqSRmlZ36FfAWyuLRQCG2/IgDqGCED5AusdKshyjS69rMf2v9WqtGC7kihe6GtXT7a8DflqvoUILZAmO3vvCbh9qhOpdx/bUbHCYKgxiFv5rjkqb1cA2xuidywURSUGgSMwcFmSofJXxI1KrmJPgWq64Ezf/Qd57FAEz2NkL8OK/9tBZknpKoTdKXK19qF6eY3SXQwRhbeMa+10Qk5LR4Hwl9iCCCWRB/qQ+2HcWo3rDbn++vMRInuqkllOakKK1Fci8JywYw7N/PRzAmjwSzKea0SqygQuG9/x5EXphKP77/9eFesu7+Dgkvs3ScRb7ablA/O2JB9ZuMMyvZ6eT5jvbaHSVPsII16hrITNq2vUsl1aDudsrqawb0pSu6zgwqYeRbG6Q7xMEDivc8o/NxxEJwEF7bPya8d5uqwu9yZOJaZJGsmkUeiuLX22XwwnPHynFJ9ZFsvly8KZBgcnuFvpbl4tFXgR9
  template:
    metadata:
      creationTimestamp: null
      name: postgis-basic-auth
      namespace: time4games-prod

