apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: time4games-prod
  labels:
    app: postgis
spec:
  ports:
    - protocol: TCP
      name: postgis
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgis
