apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis
  namespace: time4games-prod
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  serviceName: 'postgis'
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
        - name: changeowner
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/lib/postgresql/data/pgdata && chown -R 999:999 /var/lib/postgresql/data']
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgis
          image: ghcr.io/baosystems/postgis:15-3.3
          ports:
            - containerPort: 5432
              protocol: TCP
              name: postgis
          envFrom:
            - configMapRef:
                name: postgis-env
            - secretRef:
                name: postgis-env
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: 'longhorn'
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 5Gi
