apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: time4games-staging
  labels:
    app: postgis
spec:
  ports:
    - protocol: TCP
      name: postgis
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis
  namespace: time4games-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  serviceName: 'postgis'
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
        - name: changeowner
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/lib/postgresql/data/pgdata && chown -R 999:999 /var/lib/postgresql/data']
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgis
          image: ghcr.io/baosystems/postgis:15-3.3
          ports:
            - containerPort: 5432
              protocol: TCP
              name: postgis
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DB_DATABASE
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: 'longhorn'
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 2Gi
