apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: time4games-prod
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
