apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-depl
  namespace: time4games-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              memory: '256Mi'
              cpu: '0.125'
            limits:
              memory: '512Mi'
              cpu: '0.5'
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: time4games-staging
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
